{{- if .Values.pgsqlSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgsqlSecret.name }}
data:
  pgsqlDatabase: {{ .Values.pgsql.database | b64enc }}
  pgsqlUsername: {{ .Values.pgsql.username | b64enc }}
  pgsqlPassword: {{ .Values.pgsql.password | b64enc }}
{{- end }} 
