# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs: 
  kubernetes: circleci/kubernetes@1.3.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  pre-deploy:
    machine: true
    resource_class: zicodes/zero-downtime
    steps:
      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - run:
          name: "install helm"
          command: "curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash"
  build:
    environment:
      IMAGE_NAME: "zero-downtime"
      IMAGE_TAG:  $CIRCLE_SHA1
    docker:
      - image: cimg/php:8.1.5
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: "docker build and publish"
          command: "docker build -t $IMAGE_NAME:latest ."
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
  deploy:
    machine: true
    resource_class: zicodes/zero-downtime
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "helm"
          command: "/usr/local/bin/helm"
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  deploy-app:
    jobs:
      - build
      - pre-deploy
      - deploy:
          requires:
            - pre-deploy
            - build
